### ISSUE TITLE
Feature request: Interactive chart upgrades

### ISSUE THREAD

**Issue by ErroneousBosch** [Heavybullets8/heavy_script#102]
Sometimes with third party registries like truecharts, a question option will change on a chart or be added/removed. As of now there does not seem to be a way to handle this changeover and it results in an inability to directly upgrade a chart. Because these are based in the questions.yaml for the chart, Truenas just tries to apply all of your old values and then gives you nothing but errors when they don't match. 

It would be nice if a tool like this could detect these changes and allow for options to be updated.

**Comment by heavybullets8** [comment]
This will likely never be added. The original vision and it's current vision is to just use the ix-systems CLI where possible.
I especially do not want this script to also be responsible for chart migrations. I already see the issues opening up on TT-Migration and don't want the same responsibility for Heavyscript.
