### ISSUE TITLE
Feature: Enable external access to k8s API

### ISSUE THREAD

**Issue by kleinarne** [Heavybullets8/heavy_script#106]
k8s-lens cannot connect to the SCALE node by default because the kubernetes API is not exposed. Truetool had an option to expose that, and I've grown quite fond of monitoring the node with lens.

Enabling external access doesn't survive a reboot though, so it has to be activated again after every reboot. It would be great if I could do this with heavyscript too :)

**Comment by heavybullets8** [comment]
https://github.com/Heavybullets8/heavy_script#enable

Did the enable sub function --api not work?

**Comment by kleinarne** [comment]
I wasn’t aware of the arguments at all. Really sorry, should’ve read the documentation.

**Comment by heavybullets8** [comment]
It happens. Lmk if that doesn't work out.
