### ISSUE TITLE
Feature to tail container logs

### ISSUE THREAD

**Issue by noah-guillory** [Heavybullets8/heavy_script#112]
It would be nice to be able have some kind of flow to view the logs for a container under a running application. I find it very useful to look at logs to see why a container is failing to start and it would be nice to be able to do that easy in the command line rather than clicking through the SCALE UI.

I figure there must be some kind of `kubectl` incantation that will essentially do this, but it would be nice to have that also be abstracted away just like the other commands in HeavyScript.

**Comment by heavybullets8** [comment]
https://github.com/Heavybullets8/heavy_script#pod

This?

**Comment by heavybullets8** [comment]
Closing as already implemented, re-open if i have misunderstood something, thank you
