### ISSUE TITLE
[Feature Request] integrate questions.yaml and values.yaml

### ISSUE THREAD

**Issue by mritunjaymusale** [Heavybullets8/heavy_script#115]
let heavyscript access the apps question.yaml and values.yaml file that a user fills during the first installation then during updates and backups heavyscript can back those files up as well and then you can expose an option in the cli for hard-reset or hard-upgrade based on those yaml files that way the user doesn't have to refill the same ui form again when reinstalling or doing a custom major update of the app

**Comment by heavybullets8** [comment]
Thank you for the suggestion. Accessing the question.yaml and values.yaml files as described presents complexities that I currently don't have a deep understanding of, especially in the context of TrueNAS SCALE. While this feature could offer significant user convenience, its implementation goes beyond the current scope of the project. I must prioritize maintaining the project's stability and manageability, and introducing such a feature would impose a significant burden on development. I appreciate your understanding.
