### ISSUE TITLE
Handle spaces in pool names

### ISSUE THREAD

**Issue by ancashoria** [Heavybullets8/heavy_script#117]
Hi, since TrueNAS allows pool names with spaces, it would be nice if heavyscript would handle that use-case.
Here's a preview of the issue, but I'm sure there are other instances where the issue might pop up

In this case my pool is called `HDD Pool`
<img width="452" alt="Screenshot 2023-07-24 at 11 46 37 AM" src="https://github.com/Heavybullets8/heavy_script/assets/4144110/a2bd6184-2602-41fd-8b14-db0d71ccb0b9">

I think the backup command works fine, which is interesting.

**Comment by ancashoria** [comment]
omg, you fixed this? Thank you so much, I'll try it tonight

**Comment by heavybullets8** [comment]
Should be good. Tested it on a weird pool name that had 3 spaces. So should work just fine now. Let me know if that doesn't work for you.
