### ISSUE TITLE
No PVCs shown

### ISSUE THREAD

**Issue by mjforan** [Heavybullets8/heavy_script#121]
After going through the menu or running `heavyscript pvc --mount` it shows an empty list. I am on TrueNAS-SCALE-22.12.2 and the most recent version of heavyscript. I have several apps running with PVCs so there should be something displayed.

**Comment by heavybullets8** [comment]
Are you seeing any errors? Scroll up and see if you are getting ZFS errors or something.

**Comment by mjforan** [comment]
There are no errors in the terminal running heavyscript. Using journalctl shows a bunch of errors about "failed to rotate log" but that doesn't sound relevant.
![image](https://github.com/Heavybullets8/heavy_script/assets/46829130/f4566d55-9336-4b3d-8f0a-5fcd553ae305)

**Comment by heavybullets8** [comment]
```
which zfs
```

```
sudo which zfs
```

Do those show you have access to the ZFS binary?

**Comment by mjforan** [comment]
yes, `/sbin/zfs`

**Comment by heavybullets8** [comment]
```
k3s kubectl get pvc -A
```
returns?

**Comment by mjforan** [comment]
"No resources found"

**Comment by heavybullets8** [comment]
You likely do not have any PVC's then. Trucharts applications by default use PVC's as shown here:
![image](https://github.com/Heavybullets8/heavy_script/assets/20793231/824dc248-3a85-4a47-8ce0-8c9784a65e31)

**Comment by mjforan** [comment]
Okay, thank you. Sorry for the stupid question. I didn't realize the official TrueNAS apps no longer use PVCs.
