### ISSUE TITLE
Script updates and starts stopped apps

### ISSUE THREAD

**Issue by Yamon234** [Heavybullets8/heavy_script#122]
When the script runs it runs on all apps and updates them. Once the update is complete apps that we're in a "Stopped" state become active. I don't mind if it updates "Stopped" apps but it would be nice if it could stop them from starting after the update. I have several apps that I only use occasionally and don't want running all the time. 
If the script just didn't run on "Stopped" apps that would also be good.

**Comment by heavybullets8** [comment]
What version of the script are you using?

**Comment by Yamon234** [comment]
Latest version 2.1.3

**Comment by heavybullets8** [comment]
What applications are having this issue? And what chart repo are they from?

**Comment by Yamon234** [comment]
It happened with the only 2 apps I had stopped. minecraft and photoprism. Both are from Truecharts

**Comment by heavybullets8** [comment]
how were those applications stopped prior to the update? 
With the stop-all button? 
or 
Stopped from pressing the STOP button in the GUI?

**Comment by Yamon234** [comment]
Via the stop button in the gui. Not the stop all one

**Comment by heavybullets8** [comment]
I am not entirely sure why that would happen. 
The script checks to see if the start status (the status the application was in prior to updating) was Stopped, if so, it sends it to post processing, where it then waits for the application to become Active (to ensure the update was successful, and a rollback is not required) , then it returns it back to the stopped status. 

You did mention that you used the stop button in the GUI for truecharts applications though. Their devs recommend, and only support stopping their applications with the stop all button in their app config
![image](https://github.com/Heavybullets8/heavy_script/assets/20793231/1eef2ba7-d025-490e-800e-cac5102b503a)


You can provide logs, if this is something that you can replicate. 
```
bash -x ~/heavy_script/heavy_script.sh COMMAND
```

I set up my testing server to also watch for this.

**Comment by Yamon234** [comment]
Thank you, this seems to happen about half the time it updates an app that isn't running. I can provide logs if that would help, just let me know what file you need. I ran the command you gave me but the output exceeded what is viewable in the Truenas scale gui. 

I'm no programmer but I work with a few Software engineers, do you think it might help if you added a check at the very end to validate that the apps that we're told to stop actually entered a stopped state? (If that's possible)

**Comment by Yamon234** [comment]
I did some testing and stopped my normally stopped apps with the stop all button. The script reports that the app was stopped but it was active after the update. ![Screenshot_20230902_102220_Gmail.jpg](https://github.com/Heavybullets8/heavy_script/assets/141954648/32d2c446-d14e-44b2-9311-d615a166c3cf)

**Comment by heavybullets8** [comment]
To help me pinpoint the issue, please execute the following command, adapted to match your usual usage:
```
bash -x /root/heavy_script/heavy_script.sh update > /path/to/outputfile.txt 2>&1
```
Once done, please share the `outputfile.txt` with me.

Regarding the validation of the app state post-update, the script already performs this check in some ways. I share your confusion on why the apps are behaving this way.

Additionally, to better understand any potential environmental factors, could you provide the specifications of your server? Specifically:
- CPU Model and Speed
- Total RAM
- Storage type for your apps (e.g., HDD or SSD)
- Any other pertinent information

I will also need to know the flags you are using, or what settings you have changed in the config file for your update function.

**Comment by heavybullets8** [comment]
is this still an active issue you are facing?

**Comment by Yamon234** [comment]
Hey I'm sorry for the delayed reply, the last time or two the script has run I haven't seen this issue occur. I just ran it again and watched one of the apps go into an active state for a second and then be stopped. 
Specs: 
I5-10400
64Gb RAM 
2Tb SSD mirror for the apps

Here is the script I have running: 
bash /root/heavy_script/heavy_script.sh update --backup 14 --concurrent 10  --include-major --prune --rollback --sync --self-update
[outputfile.txt](https://github.com/Heavybullets8/heavy_script/files/13233024/outputfile.txt)
