### ISSUE TITLE
HeavyScript does not know how many replicas this app has

### ISSUE THREAD

**Issue by m42j** [Heavybullets8/heavy_script#134]
Got this just now (HeavyScript does not know how many replicas this app has, skipping post processing
Please submit a bug report on github so this can be fixed):

🅂 🄴 🄻 🄵
🅄 🄿 🄳 🄰 🅃 🄴
Found a new version of HeavyScript, updating myself...
Updating from: v2.3.1
Updating To: v2.4.0
Changelog:
[Features]
- Starting an app with HeavyScript will now unmount the app if it's mounted.
- CNPG database dumps no longer stop deployments by default, allowing for continuous operation.

[Refactor]
- The CNPG dump process has been refined to keep deployments running.
- Opt-in to stop deployments during the dump using the `stop_before_dump` option in the `config.ini` file.
- Your config files should have automatically updated to have this new section.

Running the new version...

🅃 🄰 🅂 🄺 :
-Backing up ix-applications dataset
Please wait..

🄱 🄰 🄲 🄺 🅄 🄿 🅂
Retention: 7

--Snapshots--
New Snapshot Name:
HeavyScript_2023_10_14_00_00_03

Deleted the oldest Snapshot(s) for exceeding limit:
HeavyScript_2023_10_07_00_00_02

🅄 🄿 🄳 🄰 🅃 🄴 🅂
Update(s) Available: 1
Asynchronous Updates: 10
Custom Timeout: 500
Image Updates: Enabled

unifi
Updated Container Image
HeavyScript does not know how many replicas this app has, skipping post processing
Please submit a bug report on github so this can be fixed

🄿 🅁 🅄 🄽 🄴
[0%] ...
[50%] Stopped containers pruned...
[100%] Successfully pruned images/containers...

----

Unifi app is linuxserver/unifi-controller:latest
TrueNAS-SCALE-22.12.3.3
cronjob command is bash /root/heavy_script/heavy_script.sh update --backup 7 --concurrent 10 --prune --rollback --include-major --self-update

**Comment by heavybullets8** [comment]
Thank you. is this an app from a chart repo? Such as Truecharts, or the Official charts?
If not, is this built from the "Launch Docker Image" button or Truecharts Custom-App?

**Comment by m42j** [comment]
It's built from "Launch Docker Image" button. I don't use Truecharts.

**Comment by heavybullets8** [comment]
Unfortunately I was not able to reproduce the error. Do you mind running this command?

```
midclt call chart.release.get_instance "$app_name" | jq '.config.controller.replicas // .config.workload.main.replicas // .pod_status.desired'
```

Replace $app_name with your apps name, such as:
```
midclt call chart.release.get_instance "unifi" | jq '.config.controller.replicas // .config.workload.main.replicas // .pod_status.desired'
```

**Comment by m42j** [comment]
```
root@nas[~]# midclt call chart.release.get_instance "unifi" | jq '.config.controller.replicas // .config.workload.main.replicas // .pod_status.desired'
1
root@nas[~]#
```

**Comment by jallen-tech** [comment]
Same issue here. 

Command below was built from the "Launch Docker Image":
root@truenas[~]# midclt call chart.release.get_instance "jellyfin" | jq '.config.controller.replicas // .config.workload.main.replicas // .pod_status.desired'
1

Command below was built from TrueCharts:
root@truenas[~]# midclt call chart.release.get_instance "nextcloud" | jq '.config.controller.replicas // .config.workload.main.replicas // .pod_status.desired'
2

**Comment by heavybullets8** [comment]
Heavyscript runs that command to see how many replicas to scale the application to.  It is unfortunately not as easy as telling the application to start, we also have to supply an integer to tell k3s how many replicas the application should be scaled to. 

What is confusing, is the error message that HeavyScript output, was due to that command returning "null". So I am wondering if k3s timed out during the script run. 

@jallen-tech are you on Truenas SCALE version: **22.12.3.3** as well?
The latest version is: **22.12.4.2** I am wondering if that has something to do with it. 

Ill keep digging in the code for now.

**Comment by heavybullets8** [comment]
Nevermind, hang tight. I found the issue.

**Comment by heavybullets8** [comment]
Changes are finally pushed. Please try the new versions lifecylce operations and let me know if that doesnt work out by re-opening this issue, thank you both. 
https://github.com/Heavybullets8/heavy_script/releases/tag/v2.4.1

**Comment by jallen-tech** [comment]
I am running "TrueNAS-SCALE-22.12.3.3". v2.4.1 resolved my issues!

You rock!
