### ISSUE TITLE
[Feature] Restart dependant containers on update

### ISSUE THREAD

**Issue by cplieger** [Heavybullets8/heavy_script#139]
Hello, I use a heavyscript cron job to update containers at night. Some of my containers are dependent upon others and thus when an update occurs these can breaks and need to be manually restarted.

A feature to address this would be great. I see 2 possible solutions:
1. A cron command with container names to restart post-update or on a timer
2.  A full config file to list dependencies

**Comment by heavybullets8** [comment]
Closing as out of the scope of the project
