### ISSUE TITLE
Suggestion for PVC storage and backup

### ISSUE THREAD

**Issue by oblique** [Heavybullets8/heavy_script#145]
Thanks for the very convenient script! I have a suggestion about backup and PVC storage.

I'm one of those people who prefer host paths mainly because if I delete an app, I don't want its data to be deleted. However I do understand the benefits of the PVC storage.

My suggestion is to be able to use `backup` to extract all the PVC storage of an app in a directory of my choice. With this way I will feel comfortable to use PVC storage for the configs and the database.

**Comment by heavybullets8** [comment]
https://github.com/Heavybullets8/heavy_script?tab=readme-ov-file#archived-repository-notice
