### ISSUE TITLE
Setting velero namespace failed

### ISSUE THREAD

**Issue by dctiger888** [Heavybullets8/heavy_script#147]
hi,

The version of my truenas scale is 13.10.0.1,and the Heavyscript is 2.7.7.  When installing velero by Heavyscript, it reported an error "Failed to set Velero namespace." 
How to solve this error? 
Thank you.

**Comment by heavybullets8** [comment]
You need to install the application from Truecharts. 
Velero is two parts. 
1. The application from Truecharts
2. The CLI (what heavyscript installs for you)

**Comment by dctiger888** [comment]
Thank you for your help, I will try.

**Comment by heavybullets8** [comment]
Re-open if this does not solve it, additionally I did update the message upon failure to set the namespace to make it more clear for users:
https://github.com/Heavybullets8/heavy_script/commit/59d3e6e4de6774df5d9bb667a890d4604e33bc14
