### ISSUE TITLE
[Feature] way of updating only 1 (or more) app - opposite of --ignore

### ISSUE THREAD

**Issue by Rayman223** [Heavybullets8/heavy_script#149]
It would be interesting if we could update just a list of apps, in other words, the opposite of --ignore.

Here's why: I have several apps. All these apps can be updated at night, but only one, Frigate, should not be updated at night but during the day to avoid stopping the recording.

Thx !

**Comment by heavybullets8** [comment]
I would like to have a user or two test these changes prior to being pushed for release.

Do so by changing branches

```sh
heavyscript git --branch
```

Then chose:
`update-list`

Once the changes are pushed to a release, the branch will be deleted, and the script will place you on the latest stable release, the next time you run `self-update`

---

Once you are on the `update-list` branch, you may test it out with the syntax below:

**Provide a comma separated list** 
```
Example: `heavyscript update -u sonarr,radarr,nextcloud
```

**or use the flag multiple times**
```
heavyscript update -u sonarr -u radarr --update-only nextcloud
```

> The list is constructed with either `-u` or `--update-only`
