### ISSUE TITLE
disable-api doesnt work

### ISSUE THREAD

**Issue by MrRulf** [Heavybullets8/heavy_script#153]
`heavyscript enable --disable-api` returns `Unknown feature: --disbale-api` on heavyscript 2.9.0

**Comment by heavybullets8** [comment]
`Unknown feature: --disbale-api`

`disbale`

Looks like you made a typo

**Comment by MrRulf** [comment]
Ur right, im stupid and misstyped it three times, thanks and sorry >.< ^^"
