### ISSUE TITLE
Suggestion: output mode brief for updates

### ISSUE THREAD

**Issue by MrWyss** [Heavybullets8/heavy_script#154]
I am running the script as chronjob, sends a mail to mailrise, which ends up as a ntfy notification to my phone.  
The output is quite verbose as for a notification. It would be great to have a brief output mode.

Sample:
Heavy Script: latest (v2.9.1) | Heavy Script: updated to v.2.9.1 (new config options)
Catalog sync duration: xx Seconds | not configured
Updates applied:
Plex: 1.40.0.7998_2.0.2 -> 1.40.1.8227_2.0.3
tailscale: 1.60.1_1.0.34 -> 1.62.0_1.0.35
other: failed -> rollback
...

or so.
thanks for the great work!

**Comment by heavybullets8** [comment]
https://github.com/Heavybullets8/heavy_script?tab=readme-ov-file#archived-repository-notice
