### ISSUE TITLE
Implement a way to purge any PV/PVCs marked as Released

### ISSUE THREAD

**Issue by kqmaverick** [Heavybullets8/heavy_script#168]
An option to purge any PV/PVCs that are no longer being used would be extremely helpful.

```k3s kubectl get pv -A | grep Released```
```zfs destroy -r <pool>/dataset/<pvc>```
```k3s kubectl delete pv <pvc>```

**Comment by heavybullets8** [comment]
https://github.com/Heavybullets8/heavy_script?tab=readme-ov-file#archived-repository-notice
