### ISSUE TITLE
local DNS resolution not working on UDM SE

### ISSUE THREAD

**Issue by pdarcos** [Heavybullets8/heavy_script#39]
Hi,
I followed your guide and did a fresh git clone a few hours ago.

I can get your script to work fine except it seems that TrueNAS Scale (22.12.0) doesn't resolve the internal DNS at all.

The strange thing is I was able to set everything up using the local DNS names instead of IPs (like jellyseer, jellyfin, etc) and when I tested the connection using DNS it worked fine.

But now it's no longer working for some reason. I SSH into TrueNAS as root and indeed the lookup fails. I'm running a UDM Special Edition with latest software updates in case that helps.

#   Name         DNS_Name                                      Port
-   ----         --------                                      ----
1)  heimdall     heimdall.ix-heimdall.svc.cluster.local        10014
2)  jellyfin     jellyfin.ix-jellyfin.svc.cluster.local        8096
3)  jellyseerr   jellyseerr.ix-jellyseerr.svc.cluster.local    10241
4)  netdata      netdata.ix-netdata.svc.cluster.local          20489
5)  prowlarr     prowlarr.ix-prowlarr.svc.cluster.local        9696
6)  qbittorrent  qbittorrent.ix-qbittorrent.svc.cluster.local  10095
7)  radarr       radarr.ix-radarr.svc.cluster.local            
8)  sonarr       sonarr.ix-sonarr.svc.cluster.local            8989
9)  vaultwarden  vaultwarden.ix-vaultwarden.svc.cluster.local  10102

root@truenas[/mnt/tank/software/scripts/heavy_script]# nslookup radarr.ix-radarr.svc.cluster.local
Server:		10.10.4.1
Address:	10.10.4.1#53

** server can't find radarr.ix-radarr.svc.cluster.local: NXDOMAIN

root@truenas[/mnt/tank/software/scripts/heavy_script]#

**Comment by heavybullets8** [comment]
What version of heavyscript are you using? You can use `bash heavyscript.sh` and it should show up under the title. But I have not used that DNS layout in a while. It should look liked this:

![image](https://user-images.githubusercontent.com/20793231/209863670-3d0d0e14-a75d-4783-bfa3-5838eeb1b079.png)

Either way though, this is likely unrelated to heavyscript
All HeavyScript does is pull the names of the applications and concatenates them together. It doesn't actually assign hostnames to your containers or anything.

**Comment by pdarcos** [comment]
I'm running latest main https://github.com/Heavybullets8/heavy_script/commit/112537ee24be71169872ec3ee406b5bd905a2238

I rebooted the Truenas machine and updated all the apps to latest version but still no luck.
Your script works as intended since I can see the hostnames and ports. I guess the issue lies elsewhere.

```
#    Name         DNS_Name                                      Port
-    ----         --------                                      ----
1)   heimdall     heimdall.ix-heimdall.svc.cluster.local        10014
2)   jackett      jackett.ix-jackett.svc.cluster.local          9117
3)   jellyfin     jellyfin.ix-jellyfin.svc.cluster.local        8096
4)   jellyseerr   jellyseerr.ix-jellyseerr.svc.cluster.local    10241
5)   netdata      netdata.ix-netdata.svc.cluster.local          20489
6)   prowlarr     prowlarr.ix-prowlarr.svc.cluster.local        9696
7)   qbittorrent  qbittorrent.ix-qbittorrent.svc.cluster.local  10095
8)   radarr       radarr.ix-radarr.svc.cluster.local            7878
9)   sonarr       sonarr.ix-sonarr.svc.cluster.local            8989
10)  vaultwarden  vaultwarden.ix-vaultwarden.svc.cluster.local  10102
root@truenas[/mnt/tank/software/scripts/heavy_script]# 
```

**Comment by heavybullets8** [comment]
Yeah, ill go ahead and close this since I don't think its related to HeavyScript, if you do come to that conclusion later though feel free to re-open.

Also feel free to message me on discord, and I will help when I have free time. 
Good luck man.

**Comment by pdarcos** [comment]
Thanks. Appreciate the fast response and your great work for the community.

Seems others are having similar problems https://www.truenas.com/community/threads/kubernetes-and-internal-dns.105210/
