### ISSUE TITLE
How to update section missing underscore

### ISSUE THREAD

**Issue by derp90** [Heavybullets8/heavy_script#40]
The section on how to update heavy_script, the example is missing an "_"

`Built-In Option (Recommended)
bash heavyscript.sh --self-update -b 10 -supr`

should be

`Built-In Option (Recommended)
bash heavy_script.sh --self-update -b 10 -supr`

**Comment by heavybullets8** [comment]
[1d5c14df2052e04e7e2a039221cc855a7f79219d](https://github.com/Heavybullets8/heavy_script/commit/1d5c14df2052e04e7e2a039221cc855a7f79219d)
