### ISSUE TITLE
backup Nextcloud database, possible?

### ISSUE THREAD

**Issue by PackElend** [Heavybullets8/heavy_script#91]
Hi,
 would like to continue the discussion happened in the comments of [Truenas Scale - Truecharts Nextcloud - Install & Restore - YouTube](https://www.youtube.com/watch?v=TQlmYxPnSrU) in regard to the backup of the Nextcloud database.

[TrueCharts is migrating](https://truecharts.org/news/breaking-enterprise-changes#configurable-cloud-native-postgresql) to [CloudNativePG - PostgreSQL Operator for Kubernetes](https://cloudnative-pg.io/) and came across [Datenbank in neue Nextcloud importieren ...  (Import database into new Nextcloud install)](https://help.nextcloud.com/t/datenbank-in-neue-nextcloud-importieren/156608), which references to [Migrating to a different server — Nextcloud latest Administration Manual latest documentation](https://docs.nextcloud.com/server/latest/admin_manual/maintenance/migrating.html)

So I'm wondering could using PostgreSQL native support for [PostgreSQL: Documentation: 15: Chapter 26. Backup and Restore](https://www.postgresql.org/docs/current/backup.html) and [PostgreSQL: Documentation: 15: Chapter 27. High Availability, Load Balancing, and Replication](https://www.postgresql.org/docs/current/high-availability.html).
The first is used in [Backup — Nextcloud latest Administration Manual latest documentation](https://docs.nextcloud.com/server/latest/admin_manual/maintenance/backup.html#backup-database)

**Comment by heavybullets8** [comment]
Thank you for bringing this issue to my attention. I understand that TrueCharts is migrating to CloudNativePG - PostgreSQL Operator for Kubernetes, and you're looking for ways to backup and restore the Nextcloud database using PostgreSQL's native support.

TrueCharts provides a guide and script for exporting PostgreSQL databases, which can be found here:
https://truecharts.org/manual/SCALE/guides/sql-export

Although it would be great to incorporate this feature into heavyscript in the future, I am currently focused on other aspects of the project. In the meantime, you can rely on the TrueCharts script for database export.

Regarding the restoration of an old database into a new one, I am not entirely certain about the process. I suggest reaching out to TrueCharts directly for assistance on this matter.

I hope this helps, and please let me know if you have any further questions or concerns.

**Comment by PackElend** [comment]
thanks for the detailed answer again.
based on the comments to the video I understood that it seems not being easily feasible, so I not even checked any guide in detail.
TrueCharts use the `pg_dump ` command as mentioned in NC documentation, so all fine 😃 

Maybe, once in not so far futur, their backup script becomes part of yours 🤞 

all said, thx again, I close the ticket 
good luck with anything
