### ISSUE TITLE
Prune gives ReadTimeoutError

### ISSUE THREAD

**Issue by bruvv** [Heavybullets8/heavy_script#95]
root@truenas[~/heavy_script]# heavyscript -p
🄿 🅁 🅄 🄽 🄴
Error: ReadTimeout(ReadTimeoutError("UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)"))

**Comment by heavybullets8** [comment]
Run the script with `bash -x heavy_script.sh -p` and show the output

**Comment by bruvv** [comment]
After I ran it again it gave no error anymore, perhaps the timeout was to little? I will close it.

**Comment by ChaosBlades** [comment]
I had this issue. I set the timeout in the config.ini to 10000 from 500 and was able to prune.
