### ISSUE TITLE
Show versions whem upgrade is held back

### ISSUE THREAD

**Issue by angst911** [Heavybullets8/heavy_script#96]
When running with -u show proposed and current version when the upgrade is held back due to major upgrade.

**Comment by heavybullets8** [comment]
@angst911 
How does this look?

```
App Name
Skipping major (chart|app) release
old full version
new version version
```

Alternatively, I can change it to:
```
App Name
Skipping major (chart|app) release
old (chart|app) version
new (chart|app) version
```

![image](https://user-images.githubusercontent.com/20793231/232697575-86b7bafe-0edd-4caf-8c3e-1bf14dbb5c6b.png)

**Comment by angst911** [comment]
Looks good to me.

**Comment by heavybullets8** [comment]
Added on latest Tag
